### PR TITLE
fixes #96 #100

### LINKED ISSUE #96: v2.0.1 throws MissingPluginException for Android
MissingPluginException is thrown when I using v2.0.1 on Android.
v2.0.0 on Android does not have this issue.
v2.0.1 on iOS does not have this issue.
Is there something I need to update to use v2.0.1 on Android?

```
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method getPage on channel flutter_plugin_pdf_viewer))
```

Thrown from:

```
/Users/user/fvm/versions/stable/packages/flutter/lib/src/services/platform_channel.dart

  @optionalTypeArgs
  Future<T?> _invokeMethod<T>(String method, { required bool missingOk, dynamic arguments }) async {
    assert(method != null);
    final ByteData? result = await binaryMessenger.send(
      name,
      codec.encodeMethodCall(MethodCall(method, arguments)),
    );
    if (result == null) {
      if (missingOk) {
        return null;
      }
      throw MissingPluginException('No implementation found for method $method on channel $name');
    }
    return codec.decodeEnvelope(result) as T?;
  }
```

Call stack:

```
MethodChannel._invokeMethod (/Users/user/fvm/versions/stable/packages/flutter/lib/src/services/platform_channel.dart:165)
<asynchronous gap> (Unknown Source:0)
PDFDocument.get (/Users/user/.pub-cache/hosted/pub.dartlang.org/advance_pdf_viewer-2.0.1/lib/src/document.dart:97)
<asynchronous gap> (Unknown Source:0)
_PDFViewerState._loadPage (/Users/user/.pub-cache/hosted/pub.dartlang.org/advance_pdf_viewer-2.0.1/lib/src/viewer.dart:151)
<asynchronous gap> (Unknown Source:0)
```

flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/user/Documents/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Nexus 5X (mobile) • 0256574f4c681f87 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.110
```

### PR DESCRIPTION
**Pull request by ncdm-stldr**

### CODE REVIEW

**Comment by ncdm-stldr** [comment]
Explanation:
- the renderer.close() sometimes creates an exception is useless because the close is already preformed by the try-catch.
- A else block has been added because it was missing (e.g. result should not been used twice).

**Comment by publiux** [comment]
This should be merged as soon as possible as this is a showstopper bug for the current flutter version.

**Comment by publiux** [comment]
Pinging @lohanidamodar

**Comment by ncdm-stldr** [comment]
Maybe I should ask to merge into develop instead : https://github.com/lohanidamodar/pdf_viewer/pull/102

**Pull request closed without merging**
