### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by maxzod**

### CODE REVIEW

**Comment by jacobpoldenzuhlke** [comment]
👍  for this PR please!

**Comment by el-mimoso** [comment]
This should be merged!

**Comment by paulo-coutinho** [comment]
????

i think this project is abandoned

**Comment by woehrer12** [comment]
+1 for this PR please!

**Review by lohanidamodar — APPROVED** [review]

**Review by lohanidamodar — CHANGES_REQUESTED** [review]
Hey can you sync with dev and resolve the conflicts.
Thank you

**Comment by jacobpoldenzuhlke** [comment]
@maxzod your turn 😺

**Comment by jacobpoldenzuhlke** [comment]
paging @lohanidamodar I can just be the annoying notification-generating person ;)

**Pull request merged**
