### PR TITLE
custom background color & custom indictor  & lazyload bug

### PR DESCRIPTION
**Pull request by kaichii**
- allow set pdf background color
 - allow custom indicator

### CODE REVIEW

**Comment by Barrier-Theo** [comment]
@kaichii Hello, interesting fix bug lazy load, Do you know when it will be up?

**Comment by kaichii** [comment]
Honestly i don't know，i use my fixed [pdf_viewer](https://github.com/kaichii/pdf_viewer) in my project.

**Comment by Barrier-Theo** [comment]
> Honestly i don't know，i use my fixed [pdf_viewer](https://github.com/kaichii/pdf_viewer) in my project.

Do you think i will be able to use your fix on my project and publish to the store?

**Comment by kaichii** [comment]
> > Honestly i don't know，i use my fixed [pdf_viewer](https://github.com/kaichii/pdf_viewer) in my project.
> 
> 
> 
> Do you think i will be able to use your fix on my project and publish to the store?

I will consider that.

**Comment by kaichii** [comment]
> > Honestly i don't know，i use my fixed [pdf_viewer](https://github.com/kaichii/pdf_viewer) in my project.
> 
> Do you think i will be able to use your fix on my project and publish to the store?

I published my fix to the pub, you can use [this](https://pub.dev/packages/easy_pdf_viewer).

**Comment by lohanidamodar** [comment]
Unable to use this, as it has changed a lot. Thank you for your initiative though.

**Pull request closed without merging**
